import fs from "node:fs/promises";
import path from "node:path";
import { slugify } from "./utils";

export async function scaffoldGreenfieldNextApp(repoDir: string, projectName: string, brief: string): Promise<void> {
  const title = projectName.trim() || "Autonomous Product";
  const description = brief.split("\n").map((line) => line.trim()).filter(Boolean).slice(0, 2).join(" ");
  const repoSlug = slugify(title) || "autonomous-product";

  const files: Record<string, string> = {
    ".gitignore": [
      "node_modules",
      ".next",
      ".vercel",
      "npm-debug.log*",
      ".env.local"
    ].join("\n"),
    "package.json": JSON.stringify(
      {
        name: repoSlug,
        private: true,
        version: "0.1.0",
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start"
        },
        dependencies: {
          next: "^15.5.14",
          react: "19.1.0",
          "react-dom": "19.1.0"
        },
        devDependencies: {
          typescript: "^5.8.3",
          "@types/node": "^22.15.17",
          "@types/react": "^19.0.10",
          "@types/react-dom": "^19.0.6"
        }
      },
      null,
      2
    ).replace('true', 'true'),
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          lib: ["dom", "dom.iterable", "es2022"],
          allowJs: false,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          incremental: true,
          module: "ESNext",
          moduleResolution: "Bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          esModuleInterop: true,
          plugins: [{ name: "next" }]
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        exclude: ["node_modules"]
      },
      null,
      2
    ).replace('false', 'false').replace('true', 'true'),
    "next-env.d.ts": [
      '/// <reference types="next" />',
      '/// <reference types="next/image-types/global" />',
      '',
      '// This file is auto-generated by Next.js.'
    ].join("\n"),
    "next.config.ts": [
      'import type { NextConfig } from "next";',
      '',
      'const nextConfig: NextConfig = {};',
      '',
      'export default nextConfig;'
    ].join("\n"),
    "app/layout.tsx": [
      'import "./globals.css";',
      'import type { Metadata } from "next";',
      '',
      'export const metadata: Metadata = {',
      `  title: ${JSON.stringify(title)},`,
      `  description: ${JSON.stringify(description || title)}`,
      '};',
      '',
      'export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {',
      '  return (',
      '    <html lang="en">',
      '      <body>{children}</body>',
      '    </html>',
      '  );',
      '}'
    ].join("\n"),
    "app/page.tsx": [
      'export default function HomePage() {',
      '  return (',
      '    <main className="shell">',
      `      <div className="badge">${title}</div>`,
      `      <h1>${title}</h1>`,
      `      <p className="lede">${description || title}</p>`,
      '      <section className="panel">',
      '        <h2>What this app is</h2>',
      `        <p>${brief.replace(/\n+/g, " ")}</p>`,
      '      </section>',
      '    </main>',
      '  );',
      '}'
    ].join("\n"),
    "app/globals.css": [
      '* { box-sizing: border-box; }',
      'body { margin: 0; font-family: Inter, Arial, sans-serif; background: #0b1020; color: #eef2ff; }',
      '.shell { max-width: 960px; margin: 0 auto; padding: 72px 20px; }',
      '.badge { display: inline-flex; padding: 6px 10px; border-radius: 999px; background: rgba(129,140,248,0.16); margin-bottom: 18px; }',
      'h1 { font-size: clamp(40px, 7vw, 78px); line-height: 0.95; margin: 0 0 16px; }',
      '.lede { font-size: 20px; color: #c5cde8; max-width: 780px; }',
      '.panel { margin-top: 32px; padding: 24px; border: 1px solid rgba(148,163,184,0.2); border-radius: 24px; background: rgba(15,23,42,0.8); }',
      'h2 { margin-top: 0; }'
    ].join("\n"),
    "README.md": [
      `# ${title}`,
      '',
      description || title,
      '',
      '## Development',
      '',
      '```bash',
      'npm install',
      'npm run dev',
      '```'
    ].join("\n")
  };

  for (const [relativePath, content] of Object.entries(files)) {
    const absolutePath = path.join(repoDir, relativePath);
    await fs.mkdir(path.dirname(absolutePath), { recursive: true });
    await fs.writeFile(absolutePath, content, "utf8");
  }
}
